### ISSUE TITLE
Firefox Extension

### ISSUE THREAD

**Issue by ppreeper** [mstuttgart/odoo-db-manager#1]
I was wondering if this could be submitted to the Firefox Extension store?

**Comment by mstuttgart** [comment]
Hi @ppreeper . Honestly, this is not in roadmap. 
I'm not familiar with firefox extensions, but I'll look into it.

**Comment by mstuttgart** [comment]
@ppreeper it here: https://addons.mozilla.org/en-US/firefox/addon/odoo-manager-database/ 😁

**Comment by ppreeper** [comment]
@mstuttgart thanks so much. I have installed it and it looks great. Thank you again for your hard work.
